# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:

#>>>>>>>>>>>>>><
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
    - id: trailing-whitespace
    - id: mixed-line-ending
    - id: check-added-large-files
      args: ['--maxkb=1000']
    - id: end-of-file-fixer
    - id: requirements-txt-fixer
    - id: check-yaml
    - id: check-json
    - id: pretty-format-json
      args: ['--autofix']
    - id: check-merge-conflict
    - id: check-case-conflict
    - id: check-docstring-first

- repo: local
  hooks:
    #  - id: isort
    #name: isort
    #stages: [commit]
    #language: system
    #entry: isort
    #types: [python]

  - id: black
    name: black
    stages: [commit]
    language: system
    entry: black
    types: [python]

  - id: flake8
    name: flake8
    stages: [commit]
    language: system
    entry: flake8
    types: [python]
    exclude: setup.py

  - id: mypy
    name: mypy
    stages: [commit]
    language: system
    entry: mypy
    types: [python]



#<<<<<<<<<<<<<<
# # isort
# -   repo: https://github.com/asottile/seed-isort-config
#     rev: v1.9.3
#     hooks:
#       - id: seed-isort-config
# - repo: https://github.com/pre-commit/mirrors-isort
#     rev: v4.3.21
#     hooks:
#       - id: isort

#-   repo: https://github.com/psf/black
#    rev: 22.3.0
#    rev: stable
#    hooks:
#    -   id: black
#        args: [--line-length=88]
        # args: [--config=pyproject.toml]

#-   repo: https://github.com/pre-commit/pre-commit-hooks
#    rev: v4.2.0
#    hooks:
#    -   id: trailing-whitespace
#    -   id: end-of-file-fixer
#    -   id: check-yaml
#    -   id: check-added-large-files
#    -   id: debug-statements
#        language_version: python3
# see also https://kontext.tech/article/954/pre-commit

# nb changes with black
#-   repo: https://github.com/PyCQA/isort
#     rev: 5.10.1
#     hooks:
#     -   id: isort
#         name: isort
#         entry: isort
#         require_serial: true
#         language: python
#         language_version: python3
#         types_or: [cython, pyi, python]
#         args: ['--filter-files']
#         minimum_pre_commit_version: '2.9.2'

#-   repo: https://github.com/asottile/pyupgrade
#    rev: v2.32.1
#    hooks:
#    -   id: pyupgrade
#        args: [--py36-plus]

#-   repo: https://github.com/pre-commit/mirrors-mypy
#    rev: v0.950
#    hooks:
#    -   id: mypy
#        language: system
#        # files: ^src/
#        args: [--strict] # --ignore-missing-imports


# -   repo: https://github.com/PyCQA/pylint
#    rev: v2.13.9
#    hooks:
#    -   id: pylint
#        name: pylint
#        entry: pylint
#        language: system
#        types: [python]
#        require_serial: true
#        args:
#            [
#            --max-args=7,
#            --max-attributes=8,
#            --ignore-imports=yes,
#            -d duplicate-code,
#            ]

#- repo: https://github.com/pycqa/flake8
#    rev: stable
#    hooks:
#      - id: flake8
#        additional_dependencies:
#          [
#            flake8-plugin,  # or some lower upper bound
#          ]
